services:
  - type: web
    name: todo
    env: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    envVars:
      - key: VITE_API_ENDPOINT
        sync: false
  - type: web
    name: todo-backend
    env: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: WEB_ORIGIN
        sync: false
