---
name: Build and Deploy in Production Environment

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: Build and Deploy in Production Environment
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build
        with:
          base-url: "/utcode-learn/"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean-exclude: pr-preview/
          folder: build
